class_name PHYReader extends RefCounted


class PHYHeader:
	static var scheme:
		get: return {
		size											= ByteReader.Type.INT,
		id												= ByteReader.Type.INT,
		solid_count										= ByteReader.Type.INT,
		checksum										= ByteReader.Type.INT,
	};

	var size: int;
	var id: int;
	var solid_count: int;
	var checksum: int;

	var address: int = 0;

	func _to_string():
		return ByteReader.get_structure_string("PHYHeader", self);

class PHYSurfaceHeader:
	static var scheme:
		get: return {
		size											= ByteReader.Type.INT,
		id												= [ByteReader.Type.STRING, 4],
		version											= ByteReader.Type.SHORT,
		model_type										= ByteReader.Type.SHORT,
		surface_size									= ByteReader.Type.INT,
		drag_axis_areas									= ByteReader.Type.VECTOR3,
		axis_map_size									= ByteReader.Type.INT,
		unused1											= [ByteReader.Type.INT, 11],
		ivps											= [ByteReader.Type.STRING, 4],
	};	

	var size: int;
	var id: String;
	var version: int;
	var surface_size: int;
	var model_type: int;
	var drag_axis_areas: Vector3;
	var axis_map_size: int;
	var unused1: Array[int] = [];
	var ivps: String;

	var solids: Array[PHYSolidHeader] = [];
	var vertices: Array[Vector3] = [];

	var address = 0;

	func _to_string():
		return ByteReader.get_structure_string("PHYSurfaceHeader", self);

class PHYLegacySurfaceHeader:
	static var scheme:
		get: return {
		mass_center										= ByteReader.Type.VECTOR3,
		rotation_inertia								= ByteReader.Type.VECTOR3,
		upper_limit_radius								= ByteReader.Type.FLOAT,
		max_deviation									= ByteReader.Type.INT,
		byte_size										= ByteReader.Type.INT,
		dummy											= [ByteReader.Type.INT, 2],
		ivps											= [ByteReader.Type.STRING, 4],
	};

	var mass_center: Vector3;
	var rotation_inertia: Vector3;
	var upper_limit_radius: float;
	var max_deviation: int;
	var byte_size: int;
	var offset_ledgetree_root: int;
	var dummy: Array[int] = [];
	var ivps: String;

	var address = 0;

	func _to_string():
		return ByteReader.get_structure_string("PHYLegacySurfaceHeader", self);

class PHYSolidHeader:
	static var scheme:
		get: return {
		vertices_offset									= ByteReader.Type.INT,
		bone_index										= ByteReader.Type.INT,
		flags											= ByteReader.Type.INT,
		face_count										= ByteReader.Type.INT,
	};

	var vertices_offset: int;
	var flags: int;
	var bone_index: int;
	var face_count: int;
	var unused1: int;
	var unused2: int;
	var unused3: int;

	var faces: Array[PHYTriangleData] = [];

	var address = 0;

	func _to_string():
		return ByteReader.get_structure_string("PHYSolidHeader", self);

class PHYTriangleData:
	static var scheme:
		get: return {
		vertex_index									= ByteReader.Type.BYTE,
		unused1											= ByteReader.Type.BYTE,
		unused2											= ByteReader.Type.UNSIGNED_SHORT,
		v1												= ByteReader.Type.SHORT,
		unused3											= ByteReader.Type.SHORT,
		v2												= ByteReader.Type.SHORT,
		unused4											= ByteReader.Type.SHORT,
		v3												= ByteReader.Type.SHORT,
		unused5											= ByteReader.Type.SHORT,
	};

	var vertex_index: int;
	var v1: int;
	var v2: int;
	var v3: int;

	var unused1: int;
	var unused2: int;
	var unused3: int;
	var unused4: int;
	var unused5: int;

	var address = 0;

	func _to_string():
		return ByteReader.get_structure_string("PHYFaceData", self);


var header: PHYHeader;
var surfaces: Array[PHYSurfaceHeader] = [];
var legacy_surfaces: Array[PHYLegacySurfaceHeader] = [];
var mdl: MDLReader;
var solid_count: int = 0; ## Somethimes the info the header is wrong so we'll count the solids count manually :C (airboat.mdl)

const TO_INCHES = 39.3700787402;
const ROT_X_NEG90		   := Basis(Vector3(1, 0, 0), Vector3(0, 0, -1), Vector3(0,  1, 0))
const ROT_X_POS90_FLIP_Y   := Basis(Vector3(1, 0, 0), Vector3(0, 0,  1), Vector3(0,  1, 0))
const ROT_Y_NEG90_FLIP_Y   := Basis(Vector3(0, 0, 1), Vector3(0, -1, 0), Vector3(-1, 0, 0))
const ROT_XZ := Basis(Vector3(0.0, 1.0, 0.0), Vector3(0.0, 0.0, 1.0), Vector3(1.0, 0.0, 0.0))

## Method to convert physics vertices to Source Engine's coordinate system. 
## It is different for each model, so we need to check the model's version and flags 
## to determine how to transform the vertices.
##
## The formula derived through experiments and tested on models up to version 49. 
## I hope it won't break :'(
func transform_vertex(vec: Vector3, bone_idx: int) -> Vector3:
	vec = vec * TO_INCHES

	var bone: MDLReader.MDLBone = mdl.bones[bone_idx] if bone_idx < mdl.bones.size() else null
	var is_autogenerated := mdl.header.flags & MDLReader.MDLFlag.AUTOGENERATED_HITBOX != 0

	if mdl.is_static_prop or (mdl.header.version <= 48 and solid_count > 1):
		return ROT_X_NEG90 * vec
	elif mdl.header.version > 48 and is_autogenerated and solid_count > 1:
		return ROT_X_POS90_FLIP_Y * vec
	elif solid_count == 1 && mdl.header.version == 48:
		return bone.pos_to_bone * (ROT_XZ * vec);
	else:
		return bone.pos_to_bone * (ROT_Y_NEG90_FLIP_Y * vec) \
			if bone != null \
			else ROT_Y_NEG90_FLIP_Y * vec;

	return vec

func _init(source_file: String, _mdl: MDLReader):
	mdl = _mdl;
	var file = FileAccess.open(source_file, FileAccess.READ);
	if file == null: return;

	header = ByteReader.read_by_structure(file, PHYHeader);

	var vertices_start = INF;

	for i in range(header.solid_count):
		var surface_header = ByteReader.read_by_structure(file, PHYSurfaceHeader);
		surfaces.append(surface_header);

		if surface_header.id != "VPHY":
			file.seek(surface_header.address);

			var legacy_surface_header = ByteReader.read_by_structure(file, PHYLegacySurfaceHeader);
			legacy_surfaces.append(legacy_surface_header);

		var vertices_count = 0;

		while file.get_position() < vertices_start:
			var solid_header = ByteReader.read_by_structure(file, PHYSolidHeader) as PHYSolidHeader;
			solid_count += 1;

			vertices_start = min(solid_header.address + solid_header.vertices_offset, vertices_start);

			surface_header.solids.append(solid_header);
	
			for j in range(solid_header.face_count):
				var triangle_data = ByteReader.read_by_structure(file, PHYTriangleData) as PHYTriangleData;
				solid_header.faces.append(triangle_data);

				vertices_count = max(vertices_count, triangle_data.v1, triangle_data.v2, triangle_data.v3);

		for j in range(vertices_count + 1):
			var vertex := ByteReader._read_data(file, ByteReader.Type.VECTOR3) as Vector3;
			var w := ByteReader._read_data(file, ByteReader.Type.FLOAT) as float;

			surface_header.vertices.append(vertex);

		vertices_start = INF;

		# NOTE: +4 means that size of header starts after the size byte
		file.seek((surface_header.address + 4) + surface_header.size);
