name: Notify
on:
  issues:
    types: [reopened, opened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: notification
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TELEGRAM_TOKEN }}
          chatId: ${{ secrets.TELEGRAM_CHAT }}
          jobStatus: ${{ job.status }}

